### ISSUE TITLE
DEFAULT_RESMGR_TPM_PORT undeclared

### ISSUE THREAD

**Issue by HaydonC** [01org/tpm2-tools#434]
The following error message shows when trying to the make the 1.x branch of this repo:

'src/common.c:241:5 error: 'DEFAULT_RESMGR_TPM_PORT' undeclared here (not in a function)'

I have installed the latest 1.x branch versions of both the tpm2-tss and tpm2-abrmd.

Running a 64-bit Ubuntu 16.04 (kernel 4.12.8) system.

Note: I'm using the 1.x branch due to the master branch build failing to initialize tcti context: 0x1

**Comment by martinezjavier** [comment]
@HaydonC this is expected.

The 1.X branch depends on the old resource manager which was removed in tpm2-tss on commit [7966ef8916f7](https://github.com/01org/tpm2-tss/commit/7966ef8916f7) ("Remove resourcemgr and fixup build.") which made to the tpm2-tss 1.1.0 release.

So if you want to use the tpm2-tools 1.X branch, then you need tpm2-tss version 1.0. Also, you don't need tpm2-abrmd with the old branch since that's the new D-Bus based resource manager.

Having said that, I didn't understand why you are not using a new tpm2-tools. The 2.X branch (which is the latest stable) should work with tpm2-tss 1.1.0 (or later) and tpm2-abrm 1.1.0.

Also since you are using a 4.12 kernel, you can also use the in-kernel resource manager instead of tpm2-abrm. Just either call your commands with -T device -d /dev/tpmrm0 or set the following env vars:

TPM2TOOLS_TCTI_NAME=device
TPM2TOOLS_DEVICE_FILE=/dev/tpmrm0

**Comment by martinezjavier** [comment]
Oh, we have in fact documented this in our [wik](https://github.com/01org/tpm2-tools/wiki)

**Comment by liuqun** [comment]
@HaydonC 
- tpm2-tss version >= 1.1.0 won't work with tpm2-tools 1.x branch
- tpm2-tss version <= 1.0 works

Just as what Javier said:
> The 1.X branch depends on the old resource manager which was removed in tpm2-tss on commit 7966ef8916f7 ("Remove resourcemgr and fixup build.") which made to the tpm2-tss 1.1.0 release.

**Comment by martinezjavier** [comment]
@williamcroberts I think this issue can be closed now.

**Comment by HaydonC** [comment]
Massive thanks guys! Should have found that answer myself but you've saved me a lot of time.

**Comment by martinezjavier** [comment]
@HaydonC you are welcome, glad that we could be of any help.

**Comment by flihp** [comment]
Hadn't seen this release mapping table. Very useful. I just converted it to a table and added a row for the latest releases. These are the versions I'm currently using. If someone else can verify I'd appreciate a second opinion.

**Comment by martinezjavier** [comment]
@flihp thanks for converting to a table, it's much nicer now.

The version you are currently using matches what we have packaged in Fedora.

BTW, tpm2-tss 1.2.0 fails to build on Fedora with GCC7 and we had to build with -Wno-int-in-bool-context. Do you want me to file an issue on tpm2-tss or should we just carry that workaround until the next release (it's already fixed in master). 

See:

https://src.fedoraproject.org/rpms/tpm2-tss/c/9eff2763287fdfaeb8124e39a68e4603a18b8594?branch=master

**Comment by flihp** [comment]
If you're willing to write the patch @martinezjavier I'll take it. I'm upgrading my dev systems which will get me a newer compiler versions so I'll probably stumble across this issue soon enough.

**Comment by martinezjavier** [comment]
@flihp sure, I'll add it in my TODO list for after the tpm2 tools options parsing porting.
